/// Generated By Bikramaditya From Fclone
import 'package:flutter/material.dart';

class FcloneConstants {
  static var color = Color(0xffff6347);
  static var logoBackColor = Colors.white;
  static var appBarColor = Colors.white;
  static var appName = "BlaBlaStay";
  static var url = "https://blablastay.com/";
  static var logoFullTrans = "assets/logos/logo_full_trans.png";
}
